Feature Splitter function and tests added.
UBC-MDS/DSCI_524_Group2_Python pull request #37
Opened 2020-03-04 05:54 UTC by eyrakas

2020-03-05 22:13 UTC, andrealee011 requested changes
pyb4model/__pycache__/
pyb4model.egg-info/
should not be commited to the repo

2020-03-05 22:14 UTC, andrealee011 commented
poetry.lock might need to be deleted to resolve merge conflict (as per tiffany's comments in class)

2020-03-06 00:08 UTC, eyrakas commented
I have deleted the above files from the PR.

2020-03-06 05:09 UTC, andrealee011 approved these changes

2020-03-06 20:59 UTC, merged